### ISSUE TITLE
编译的时候提示错误

### ISSUE THREAD

**Issue by keigoliye** [jardenliu/wepy-plugin-iview#12]
使用wepy build --no-cache编译的时候出现下面的错误，无法编译完成。
[Error] SyntaxError: unknown: Unexpected token (14:8)
  12 |
  13 |     data: {
> 14 |         ...default_data
     |         ^
  15 |     },
  16 |
  17 |     methods: {
    at Parser.pp$5.raise (E:\workspace\Rel\wepy_test\node_modules\babylon\lib\index.js:4454:13)
    at Parser.pp.unexpected (E:\workspace\Rel\wepy_test\node_modules\babylon\lib\index.js:1761:8)
    at Parser.pp$3.parseIdentifier (E:\workspace\Rel\wepy_test\node_modules\babylon\lib\index.js:4332:10)
    at Parser.pp$3.parsePropertyName (E:\workspace\Rel\wepy_test\node_modules\babylon\lib\index.js:4156:96)
    at Parser.pp$3.parseObj (E:\workspace\Rel\wepy_test\node_modules\babylon\lib\index.js:4045:12)
    at Parser.pp$3.parseExprAtom (E:\workspace\Rel\wepy_test\node_modules\babylon\lib\index.js:3719:19)
    at Parser.pp$3.parseExprSubscripts (E:\workspace\Rel\wepy_test\node_modules\babylon\lib\index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (E:\workspace\Rel\wepy_test\node_modules\babylon\lib\index.js:3474:19)
    at Parser.pp$3.parseExprOps (E:\workspace\Rel\wepy_test\node_modules\babylon\lib\index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (E:\workspace\Rel\wepy_test\node_modules\babylon\lib\index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (E:\workspace\Rel\wepy_test\node_modules\babylon\lib\index.js:3344:19)
    at Parser.pp$3.parseObjectProperty (E:\workspace\Rel\wepy_test\node_modules\babylon\lib\index.js:4115:99)
    at Parser.pp$3.parseObjPropValue (E:\workspace\Rel\wepy_test\node_modules\babylon\lib\index.js:4140:84)
    at Parser.pp$3.parseObj (E:\workspace\Rel\wepy_test\node_modules\babylon\lib\index.js:4048:10)
    at Parser.pp$3.parseExprAtom (E:\workspace\Rel\wepy_test\node_modules\babylon\lib\index.js:3719:19)
    at Parser.pp$3.parseExprSubscripts (E:\workspace\Rel\wepy_test\node_modules\babylon\lib\index.js:3494:19)

**Comment by jardenliu** [comment]
信息太少，看不出问题
