### ISSUE TITLE
好像少了copy-dir

### ISSUE THREAD

**Issue by hawkefly** [jardenliu/wepy-plugin-iview#4]
➜  itracker git:(master) ✗ wepy build --watch 
{ Error: Cannot find module 'copy-dir'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/liwei/WebstormProjects/itracker/node_modules/wepy-plugin-iview/src/index.js:9:15)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.load (/usr/local/lib/node_modules/wepy-cli/lib/loader.js:113:17)
    at Object.loadPlugin (/usr/local/lib/node_modules/wepy-cli/lib/loader.js:131:24)
    at Object.checkPlugin (/usr/local/lib/node_modules/wepy-cli/lib/compile.js:187:33)
    at Object.init (/usr/local/lib/node_modules/wepy-cli/lib/compile.js:221:60) code: 'MODULE_NOT_FOUND' }
[WARNING] 找不到插件：wepy-plugin-iview。
^C

**Comment by jardenliu** [comment]
感谢你的反馈！稍后修正。

**Comment by jardenliu** [comment]
#3
