### ISSUE TITLE
更新插件失败

### ISSUE THREAD

**Issue by jixieshi999** [jardenliu/wepy-plugin-iview#7]
在执行build的时候报错，提示找不到json文件，但是已经安装了
[17:36:53] [完成] 已完成安装 wepy-plugin-iview，重新启动编译。
重新编译还报错
Error: Cannot find module 'iview-weapp/package.json'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.resolve (internal/module.js:18:19)

**Comment by jardenliu** [comment]
删除node_modules和package-lock.json，重新npm i
